# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 20:47
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Roller Image')),
                ('index', models.IntegerField(default=0, verbose_name='Rolling Sequence')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name_plural': 'Slider Image',
                'verbose_name': 'Slider Image',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='Product SKU')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Product Name')),
                ('goods_size', models.CharField(blank=True, choices=[('OneSize', 'OneSize'), ('29x32', '29x32'), ('30x32', '30x32'), ('31x32', '31x32'), ('32x32', '32x32'), ('33x32', '33x32'), ('34x32', '34x32'), ('36x32', '36x32'), ('38x32', '38x32'), ('xsmall', 'xsmall'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('xlarge', 'xlarge'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('other', 'other')], max_length=10, null=True, verbose_name='Product Size')),
                ('goods_color', models.CharField(blank=True, choices=[('OneColor', 'OneColor'), ('red', 'Red'), ('blue', 'Blue'), ('pink', 'pink'), ('black', 'black'), ('white', 'white'), ('green', 'green'), ('grey', 'grey'), ('other', 'other')], max_length=10, null=True, verbose_name='Available Color')),
                ('click_num', models.IntegerField(default=0, verbose_name='Click Times')),
                ('sold_num', models.IntegerField(default=0, verbose_name='Sold Quantity')),
                ('fav_num', models.IntegerField(default=0, verbose_name='Total Favorite')),
                ('goods_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='Inventory')),
                ('market_price', models.FloatField(default=0.0, verbose_name='Market Price')),
                ('shop_price', models.FloatField(default=0.0, verbose_name='Price in Store')),
                ('goods_brief', models.TextField(max_length=100, verbose_name='Product Brief Intro')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='Product Detail')),
                ('ship_free', models.BooleanField(default=False, verbose_name='Free delivery')),
                ('goods_front_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Home Page Product Image')),
                ('is_new', models.BooleanField(default=False, verbose_name='New Arrival')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Popular Product')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name_plural': 'Product Detail',
                'verbose_name': 'Product Detail',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Category Name', max_length=30, verbose_name='Category Name')),
                ('code', models.CharField(default='', help_text='Category Code', max_length=30, verbose_name='Category Code')),
                ('desc', models.TextField(default='Some Category Description...', help_text='Category Description', verbose_name='Category Description')),
                ('category_type', models.IntegerField(choices=[(1, 'First Category'), (2, 'Second Category'), (3, 'Third Category'), (4, 'Fourth Category')], help_text='Category Type', verbose_name='Category Type')),
                ('is_tab', models.BooleanField(default=False, help_text='On Navigation Bar', verbose_name='On NaviBar')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name_plural': 'Goods Category',
                'verbose_name': 'Goods Category',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Brand Name', max_length=30, verbose_name='Brand Name')),
                ('desc', models.TextField(default='', help_text='Brand Description', max_length=500, verbose_name='Brand Description')),
                ('image', models.ImageField(max_length=200, upload_to='brand/image/')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='Brand Category')),
            ],
            options={
                'verbose_name_plural': 'Product Brand',
                'verbose_name': 'Product Brand',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Product Image')),
                ('image_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='image url')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='Product Name')),
            ],
            options={
                'verbose_name_plural': 'Item Image Roller',
                'verbose_name': 'Item Image Roller',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategoryBrand', verbose_name='Product Brand'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Product Name'),
        ),
    ]
