# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180817_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_color',
            field=models.CharField(blank=True, choices=[('OneColor', 'OneColor'), ('red', 'Red'), ('blue', 'Blue'), ('pink', 'pink'), ('black', 'black'), ('white', 'white'), ('green', 'green'), ('grey', 'grey'), ('other', 'other')], default='OneColor', max_length=10, null=True, verbose_name='Available Color'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_size',
            field=models.CharField(blank=True, choices=[('OneSize', 'OneSize'), ('29x32', '29x32'), ('30x32', '30x32'), ('31x32', '31x32'), ('32x32', '32x32'), ('33x32', '33x32'), ('34x32', '34x32'), ('36x32', '36x32'), ('38x32', '38x32'), ('xsmall', 'xsmall'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('xlarge', 'xlarge'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('other', 'other')], default='OneSize', max_length=10, null=True, verbose_name='Product Size'),
        ),
    ]
