# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180818_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.GoodsCategory', verbose_name='Category the Ad belongs')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Goods', verbose_name='Goods in Index Ad')),
            ],
            options={
                'verbose_name_plural': 'Ads for Category on Index',
                'verbose_name': 'Ads for Category on Index',
            },
        ),
    ]
