# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20180827_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='nums',
            new_name='goods_num',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('success', 'Paid'), ('cancelled', 'Cancelled'), ('pending', 'To Pay')], default='pending', max_length=20, null=True, verbose_name='Payment Status'),
        ),
    ]
