# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20180827_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='email',
            field=models.CharField(default='', max_length=200, verbose_name='Receipt Email'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='Order Information'),
        ),
    ]
