# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180813_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Firstname'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Lastname'),
        ),
    ]
