# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180814_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Last Name'),
        ),
    ]
