# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180824_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membershipNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Membership Card'),
        ),
    ]
