# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='', max_length=100, verbose_name='District')),
                ('address', models.CharField(default='', max_length=200, verbose_name='User Address')),
                ('signer_name', models.CharField(default='', max_length=100, verbose_name='Signer')),
                ('signer_mobile', models.CharField(default='', max_length=10, verbose_name='Signer Phone Number')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name_plural': 'User Address',
                'verbose_name': 'User Address',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name_plural': 'User Favorite Items',
                'verbose_name': 'User Favorite Items',
            },
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.IntegerField(choices=[(1, 'Feedback About Products'), (2, 'Complain'), (3, 'Gift Card'), (4, 'Shipping & Handling'), (5, 'Return & Exchange'), (6, 'Product Inquiries'), (7, 'Payment')], default=1, help_text='Message Type: 1: Feedback About Products, 2: Complain, 3: Gift Card, 4: Shipping & Handling, 5: Return & Exchange, 6: Product Inquiries, 7: Payment', verbose_name='Message Type')),
                ('subject', models.CharField(default='', help_text='Message Subject', max_length=100, verbose_name='Message Subject')),
                ('message', models.TextField(default='', help_text='Message', max_length=1000, verbose_name='Message')),
                ('file', models.FileField(help_text='Files to Upload', upload_to='file/usermsg/', verbose_name='Files to Upload')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name_plural': 'User Messages',
                'verbose_name': 'User Messages',
            },
        ),
    ]
