# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20180821_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='Product ID', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Product Name'),
        ),
    ]
