# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20180824_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'Shipment Address', 'verbose_name_plural': 'Shipment Address'},
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='district',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='apt_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartment Number'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(blank=True, default='Quebec', max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street'),
        ),
    ]
