# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20180825_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessages',
            old_name='user',
            new_name='username',
        ),
    ]
