# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0012_auto_20180825_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='email',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Email For Shipping'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='apt_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartment Number For Shipping'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City For Shipping'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postcode For Shipping'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='province',
            field=models.CharField(blank=True, default='Quebec For Shipping', max_length=20, null=True, verbose_name='Province For Shipping'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street For Shipping'),
        ),
    ]
